repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Version stable de Black
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "120"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0  # Version stable de Flake8
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=120"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Spécification de la version stable de isort
    hooks:
      - id: isort

  - repo: local  # Utilisation de Pylint via une installation locale
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        additional_dependencies: [pylint]

