# -*- coding: utf-8 -*-
"""\brief Calculate semiconductor losses with IEC TC 22 formulas.

This module is part of the PELCA reliability evaluator.
"""

# note: the standard gives formulas to determine the avg losses (conduction / switching) affecting a device (diode / igbt)
# during one period of output current. The purpose is to enable calculation of losses of the whole inverter stage.
# Here we consider that each leg of inverter is composed of two HB connected in //. The losses are calculated for devices within on HB.

# possible enhancements: number of modules connected in // might be parameterized (1 .. N), data coming from Excel sheet
# m can possibly change depending on relative_speed parameter of mission profile => need to update m from class
# PF can also be modified depending on relative_torque requested


import math

class IEC_TC_22_calc_losses():

    """Represent i e c t c 22 calc losses behavior used by reliability calculations."""
    def __init__(self, fsw: int = 2000, PF: float=0.8, m: float=0.7, nb_parallel_modules=2):
        """Initialize the object with the provided configuration."""
        self.fsw = fsw
        self.PF  = PF
        self.m   = m
        self.nb_parallel_modules = nb_parallel_modules

    # ==============================================================================================
    # assumption : two HB modules in parallel (per leg) => full inverter: 3 legs <=> 6 half bridges
    # ==============================================================================================
    # returns the avg losses for one HB, over one period of output current:
    #  PL_on_T_HB : on-state losses of one transistor of one half bridge
    #  PL_on_D_HB : on-state losses of one diode of one half bridge
    #  PL_sw_T_HB : switching losses of one transistor of one half bridge
    #  PL_sw_D_HB : switching losses (recovery) of one diode of one half-bridge
    #
    # 2 diodes & 2 transistors per half-bridge module
    # => total losses per power module = 2*(PL_on_T_HB+PL_on_D_HB+PL_sw_T_HB+PL_sw_D_HB)
    #
    # total losses generated by the 6 power modules: 12*(PL_on_T_HB+PL_on_D_HB+PL_sw_T_HB+PL_sw_D_HB)

    def calc_losses(self, m, Iout, Ir_out, Udc, UT_th, UT_r, UD_th, UD_r, ET, ED):
        """

        Parameters
        ----------
        m : float
            modulation index.
        Iout : float
            inverter output current.
        Ir_out : float
            inverter output rated current.
        Udc : float
            DC bus voltage.
        UT_th : float
            IGBT threshold voltage (on characteristic).
        UT_r : float
            on state dynamic resistance.
        UD_th : float
            diode threshold voltage (during conduction of diode).
        UD_r : float
            on state dynamic resistance
        ET : float
            igbt (transistor) switching energy.
        ED : float
            diode switching energy.

        Returns
        -------
        PL_on_T_HB : float
            DESCRIPTION.
        PL_on_D_HB : float
            DESCRIPTION.
        PL_sw_T_HB : float
            DESCRIPTION.
        PL_sw_D_HB : float
            DESCRIPTION.

        """
        fsw=self.fsw  # params.get('fsw', 2000)
        # 4 000 for a CDM up to 90 kW
        # 2 000 for a CDM above 90 kW

        PF = self.PF  # params.get('PF', 0.8)

        # validity: pwm freq >= 15 ... 20 x fundamental freq of motor current
        #
        # calculation according to IEC-TC_1.pdf (p85...)
        sqrt2 =  math.sqrt(2)
        cos_phy=PF # phy=phase angle between fundamental of voltage & current motor

        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        # m=self.m   # 0.7 # modulation index, supposed to be identical to the relative CDM output freq up to rated output freq
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        # Motor cable current, relevant for increased switching losses
        # Imotor_cable changes with motor current
        # Imotor_cable= params.get('Imotor_cable', 10)
        if Iout<4:
            Imotor_cable = 4 # Imotor_cable = 4 for Ir,out <= 4 A
        else:
            if Iout<10:
                Imotor_cable = Iout # Imotor_cable = ir,out for 4 A < Ir,out < 10 A
            else:
                Imotor_cable=10 # Imotor_cable = 10 for Ir,out >= 10 A

        # !!!!!!!!!!!!!!
        Imotor_cable = 0  # not considered for pwm estimation of losses
        # !!!!!!!!!!!!!!

        # calculation of losses according to IEC - TC 22-SC 22G

        # transistor on state losses
        PL_on_T    = (sqrt2*Iout*UT_th*(  (1/(2*math.pi))
                                        + (1.22*m*cos_phy)/8)
                      + ((UT_r-UT_th)/Ir_out) * 2*(Iout**2) * (1/8 + (1.22*m*cos_phy)/(3*math.pi))) # for single power module

        # <output current will be shared in 2 IGBT in //>
        PL_on_T_HB = (sqrt2*(Iout/self.nb_parallel_modules)*UT_th*(  (1/(2*math.pi))
                                                                   + (1.22*m*cos_phy)/8)
                      + ((UT_r-UT_th)/Ir_out) * 2*((Iout/self.nb_parallel_modules)**2) * (1/8 + (1.22*m*cos_phy)/(3*math.pi))) #

        # note: PL_on_T_HB != PL_on_T/2

        # freewheeling diode on state losses
        PL_on_D    = (sqrt2*Iout*UD_th*(  (1/(2*math.pi))
                                        - (1.22*m*cos_phy)/8)
                      + ((UD_r-UD_th)/Ir_out) * 2*(Iout**2) * (1/8 - (1.22*m*cos_phy)/(3*math.pi))) # for single power module

        # <output current will be shared in 2 diodes in //>
        PL_on_D_HB = (sqrt2*(Iout/self.nb_parallel_modules)*UD_th*(  (1/(2*math.pi))
                                                                   - (1.22*m*cos_phy)/8)
                      + ((UD_r-UD_th)/Ir_out) * 2*((Iout/self.nb_parallel_modules)**2) * (1/8 - (1.22*m*cos_phy)/(3*math.pi))) # in each HB
        # note: PL_on_D_HB != PL_on_D/2

        # transistor switching losses
        PL_sw_T    = (ET/math.pi) * Udc * sqrt2 * (Iout + Imotor_cable)*fsw             # for single power module

        # <output current will be shared in 2 IGBT in //>
        # PL_sw_T_HB = ET * Vdc * Idc_equ with Idc_equ = sqrt(2)*(Iout+Imotor_cable)/pi
        PL_sw_T_HB = (ET/math.pi) * Udc * sqrt2 * ((Iout/self.nb_parallel_modules) + (Imotor_cable/self.nb_parallel_modules))*fsw     # for each half bridge: PL_sw_T_HB (= PL_sw_T/2)

        # freewheeling diode switching losses
        PL_sw_D = (ED/math.pi) * Udc * sqrt2 * (Iout + Imotor_cable)*fsw                # for single power module

        # <output current will be shared in 2 diodes in //>
        PL_sw_D_HB = (ED/math.pi) * Udc * sqrt2 * ((Iout/self.nb_parallel_modules) + (Imotor_cable/self.nb_parallel_modules))*fsw     # PL_sw_D_HB = PL_sw_D/2

        return PL_on_T_HB, PL_on_D_HB, PL_sw_T_HB, PL_sw_D_HB


if __name__ == '__main__':


    # # Hack de test uniquement
    # import sys
    # from pathlib import Path
    # # Ajouter la racine du projet au sys.path
    # ROOT = Path(__file__).resolve().parents[2]  # adapte le niveau si besoin
    # sys.path.insert(0, str(ROOT))

    # every execution will add the path...


    #from ..components.DeviceParameters import DeviceParameters # to copy in that folder for local test...
    from inverter_reliability.igbt_reliability.components.DeviceParameters import DeviceParameters


    # check

    nb_parallel_modules = 2
    params = {}
    reference_module = DeviceParameters(params)

    Rth_heatsink = 0.2085 #params.get('Rth_heatsink', 0.2085)

    #Iout = params.get('Ir_out', 490)
    Udc = 540      # DC bus voltage
    # rated CDM output current, RMS value
    Ir_out = 363   # 490 initially
    Iout = 363     # output current RMS (normally 363 at PN) : 3*230*363*0.8 = 200376 ~ 200K

    Icond = Iout   # conduction current per "switch" (composed of two modules in //))

    Tj_igbt = 80   # assumption - initial guess
    Tj_diode = 80  #

    Ta = 25        # degC ambient temperature
    m = 1         # full speed

    HB_losses = IEC_TC_22_calc_losses(fsw=2000, PF=0.8, m=m, nb_parallel_modules=nb_parallel_modules)

    # after estimation of losses, the avg temperature can be estimated by considering that junction temperature
    # will reach rapidly steady state => Tj_ibgt = Tcase + Rth_jc_igbt*P_igbt, with Tcase = P_igbt*0.25K/W + Ta

    # make a few iterations util Tj_diode and Tj_IGBT stabilizes
    for i in range(6):

        #debug
        print(f"IEC_TC_22_calc_losses: Tj_igbt: {Tj_igbt} Tj_diode: {Tj_diode}")

        # transistor parameters for on state losses calculation
        UT_th = reference_module.UT_th(Tj_igbt, Icond) # Threshold voltage of the power transistor (IGBT)
        UT_r = reference_module.UT_r(Tj_igbt,  Icond) # reference power module : Vcesat_terminals = 1.90V (@600A, Tvj=150degC)

        # diode parameters for on state losses calculation
        UD_th = reference_module.UD_th(Tj_diode, Icond)  # Threshold voltage  of the power diode
        UD_r = reference_module.UD_r(Tj_diode, Icond)   # On state voltage of the power diode at rated CDM output current
        # reference power module : Vec_terminals = 1.95V (@600A, Tvj=150degC)

        # for transistor switching losses calculation (J/VA)
        ET = reference_module.ET(Tj_igbt, Udc, Iout/nb_parallel_modules, reference_module.Rg)*1e-3  # Switching loss energy of the power transistor (IGBT) per volt and per ampere

        # for diode switching losses calculation (J/VA)
        ED = reference_module.ED(Tj_diode, Udc, Iout/nb_parallel_modules, reference_module.Rg)*1e-3  # Switching loss energy of the power diode per volt and per ampere

        # calculation of avg losses affecting one IGBT, one diode in a HB during a period of output current:
        PL_on_T_HB, PL_on_D_HB, PL_sw_T_HB, PL_sw_D_HB = HB_losses.calc_losses(m, Iout, Ir_out, Udc, UT_th, UT_r, UD_th, UD_r, ET, ED)

        # losses for whole inverter: (2 IGBTs + 2 diodes) per HB, 6 HB (since 2 HB per leg) => 2*6 IBTs + 2*6 diodes
        total_loss = (PL_on_T_HB + PL_sw_T_HB) * nb_parallel_modules*6 + (PL_on_D_HB +  PL_sw_D_HB) * nb_parallel_modules*6

        # estimation of heatsink temperature
        module_losses = 2 * (PL_on_T_HB + PL_sw_T_HB + PL_on_D_HB +  PL_sw_D_HB)
        Th = Ta + Rth_heatsink * module_losses

        # update  junction temperatures:
        Tj_igbt  = Th + (PL_on_T_HB+PL_sw_T_HB)*(reference_module.Rth_jc_Q*1e-3)
        Tj_diode = Th + (PL_on_D_HB+PL_sw_D_HB)*(reference_module.Rth_jc_D*1e-3)

    # display final estimation
    print("results:")
    print(f"IEC_TC_22_calc_losses: Tj_igbt: {Tj_igbt} Tj_diode: {Tj_diode}")
    print("IEC_TC_22_calc_losses: Th:", Th, "(degC)")
    print("IEC_TC_22_calc_losses: (one IGBT)  PL_on_T_HB:" , PL_on_T_HB, "W")
    print("IEC_TC_22_calc_losses: (one diode) PL_on_D_HB:" , PL_on_D_HB, "W")
    print("IEC_TC_22_calc_losses: (one IGBT)  PL_sw_T_HB:" , PL_sw_T_HB, "W")
    print("IEC_TC_22_calc_losses: (one diode) PL_sw_D_HB:" , PL_sw_D_HB, "W")
    print("IEC_TC_22_calc_losses: total losses for the inverter = ",total_loss,"W")

    # ================================================================================================
    # remark:
    # to simulate the deltaT of dies, might generate a repetitive pattern
    # of power pulse (amplitude = avg power processed by die):

    #                avg(P_total_Sc)  between 0 and Tout/2
    #                avg(P_total_D'c) between 0 and Tout/2
    #                avg(P_total_S'c) between Tout/2 and Tout
    #                avg(P_total_Dc)  between  Tout/2 and Tout

    #                avg(P_total_S'b) between 0 and Tout/6
    #                avg(P_total_Db)  between 0 and Tout/6
    #                avg(P_total_Sb)  between Tout/6 and 4*Tout/6
    #                avg(P_total_D'b) between Tout/2 and 4*Tout/6
    #                avg(P_total_S'b) between 4*Tout/6 and Tout
    #                avg(P_total_Db)  between 4*Tout/6 and Tout

    #                avg(P_total_Sa)  between 0 and Tout/3
    #                avg(P_total_D'a) between 0 and Tout/3
    #                avg(P_total_S'a) between Tout/3 and 5*Tout/6
    #                avg(P_total_Da)  between Tout/3 and 5*Tout/6
    #                avg(P_total_Sa)  between 5*Tout/6 and Tout
    #                avg(P_total_D'a) between 5*Tout/6 and Tout
    #
    # This pattern of power pulses provided to the thermal models would allow to
    # determine the deltaT of the dies

    # if no thermal coupling of dies is considered, it can be further simplified by simply applying the the losses of
    # one switch (or diode) during 50% of time
    # thermal simulation by feeding a thermal model (evaluated for instance at Fsw) that represent the thermal path between
    # die and ambient by a nth order forster model
    # ====================================================================================================
